apiVersion: apps/v1
kind: Deployment
metadata: 
  name: syghtings-server-deployment
  labels:
    app: syghtings-server
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: syghtings-server
  template:
    metadata: 
      labels:
        app: syghtings-server
    spec:
      containers:
      - name: syghtings-server
        image: maurosoppelsa/syghtings_server:latest
        ports:
        - containerPort: 3000
        
---
apiVersion: v1
kind: Service
metadata:
 name: syghtings-server-service
spec:
  selector:
    app: syghtings-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 