version: '3'
services:
  syghtings-server:
    image: syghtings-server:latest
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    environment:
      MONGO_URI: "mongodb://mongodb:27017/syghtings-db"
      SIGHT_IMAGE_DIRECTORY: "../../sight-photos"
      LOG_DIR: "/../../logs"
      PORT: 3000
    depends_on:
      - mongodb
    volumes:
      - ~/projects/syghtings-server/sight-photos:/home/node/app/sight-photos
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: sygthings-db
    ports:
      - 27017:27017
    volumes: 
      - ~/projects/syghtings-server/mongo/data:/data/db

